# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('comments', models.CharField(max_length=255, verbose_name='Coment\xe1rios')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_categories.BookCategory', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
            },
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(max_length=255, verbose_name='Descri\xe7\xe3o')),
                ('featured_internal', models.BooleanField(default=False, verbose_name='Foto de destaque')),
                ('image', models.ImageField(upload_to='books/', verbose_name='Imagem')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.Book')),
            ],
            options={
                'verbose_name': 'Imagem do livro',
                'verbose_name_plural': 'Imagens do livro',
            },
        ),
    ]
