# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_publishing_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Coment\xe1rios'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
