# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20160212_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default=datetime.datetime(2016, 2, 12, 18, 32, 40, 185582, tzinfo=utc), max_length=255, verbose_name='Idioma'),
            preserve_default=False,
        ),
    ]
