# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ano',
            field=models.CharField(default=datetime.datetime(2016, 2, 12, 19, 12, 21, 699547, tzinfo=utc), max_length=4, verbose_name='Ano'),
            preserve_default=False,
        ),
    ]
