# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ano',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing_house',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editora'),
        ),
    ]
