# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books_categories.BookCategory', verbose_name='Categoria Pai')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categoria de Livro',
                'verbose_name_plural': 'Categorias dos Livros',
            },
        ),
    ]
