# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='adress',
            field=models.CharField(default=datetime.datetime(2016, 2, 12, 18, 56, 56, 860327, tzinfo=utc), max_length=255, verbose_name=b'Endereco'),
            preserve_default=False,
        ),
    ]
